"""Initial migration after fixing models

Revision ID: 0cc7714b2314
Revises: 
Create Date: 2025-01-06 20:11:32.435890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc7714b2314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('spaces', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rides_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'REJECTED', 'IN_PROGRESS', name='bookingstatus'), nullable=True),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_bookings_ride_id_rides')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ride',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_user_ride_ride_id_rides')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_ride_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'ride_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ride')
    op.drop_table('bookings')
    op.drop_table('rides')
    op.drop_table('users')
    # ### end Alembic commands ###
