"""empty message

Revision ID: ade1989f9141
Revises: 
Create Date: 2024-12-06 14:10:10.649422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade1989f9141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_horses_owner_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('spaces', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rides_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('horse_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'REJECTED', 'IN_PROGRESS', name='bookingstatus'), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('fk_bookings_horse_id_horses')),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_bookings_ride_id_rides')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ride',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_user_ride_ride_id_rides')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_ride_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'ride_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ride')
    op.drop_table('bookings')
    op.drop_table('rides')
    op.drop_table('horses')
    op.drop_table('users')
    # ### end Alembic commands ###
