"""fixing

Revision ID: cbb341818ddb
Revises: e3e5c623857c
Create Date: 2025-01-08 12:49:27.054638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb341818ddb'
down_revision = 'e3e5c623857c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rides_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_rides_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
